name: jmusicbot
services:
  jmusicbot:
    image: ghcr.io/yojoshb/jmusicbot-docker:latest
    container_name: jmusicbot
    volumes:
      - /DATA/AppData/$AppID/config:/config

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: jmusicbot
  description:
    en_us: A cross-platform Discord music bot with a clean interface, and that is easy to set up and run yourself!
  tagline:
    en_us: JMusicBot
  developer: yojoshb
  author: Discord-Bot
  icon: https://jmusicbot.com/assets/images/logo.png
  thumbnail: ""
  tips:
    before_install:
      en_us: JMusicBot Docs https://jmusicbot.com/
  title:
    en_us: JMusicBot
  category: Discord-Bot